# Generated by Django 4.2.27 on 2026-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_rolecategory_service_teammember_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('$1k-$3k', '$1,000 - $3,000 / month'), ('$3k-$5k', '$3,000 - $5,000 / month'), ('$5k-$10k', '$5,000 - $10,000 / month'), ('$10k+', '$10,000+ / month')], help_text='Select your budget range', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, choices=[('immediately', 'Immediately (ASAP)'), ('1_month', 'Within 1 month'), ('1_3_months', '1-3 months'), ('exploring', 'Just exploring')], help_text='When do you need to hire?', max_length=50),
        ),
    ]
