"""
Django settings for remdesk_project project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') + ['.vercel.app', 'now.sh', 'remdeskjobs.com', 'www.remdeskjobs.com']

# Vercel/Production Proxy Settings (CRITICAL for OAuth)
# ----------------------------------------------------------------
# Trust the "X-Forwarded-Proto" header coming from Vercel's load balancer.
# Without this, Django thinks requests are HTTP, and secure cookies (OAuth state) are dropped.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Cloudinary storage (Must be before staticfiles)
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter', # For X

    'core',
    'talenthub',

    # Cloud Storage for file uploads (resumes)
    # 'cloudinary_storage' moved to top
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # CurrentSiteMiddleware removed - causing 500s. Rely on SITE_ID=1
    "allauth.account.middleware.AccountMiddleware",
    "csp.middleware.CSPMiddleware",
    # Safe Caching: Prevent HTML caching so Nonce is always fresh
    "core.middleware.SecurityHeadersMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth Settings
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'none' # For development simplicity

# Provider Config (Placeholders)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
         'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Social Login: Skip the confirmation page and login immediately
SOCIALACCOUNT_LOGIN_ON_GET = True

ROOT_URLCONF = 'remdesk_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'remdesk_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Production Database (Neon/Postgres)
# If DATABASE_URL is present, it will override the default SQLite
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise Storage (Compression & Caching)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary: Cloud storage for file uploads (resumes, docs)
# Credentials come from env vars — get them at https://console.cloudinary.com
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'SECURE': True,  # Force HTTPS
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'

# Email Backend Configuration
if DEBUG:
    # Use console backend for development output
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Use SMTP for production or when DEBUG is False
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Security Hardening (PageSpeed Insights Fixes)
# ---------------------------------------------------------

# 1. Strict Transport Security (HSTS)
# Forces browsers to use HTTPS for 1 year
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# 2. Content Security Policy (CSP)
# Note: CSPMiddleware is already in the MIDDLEWARE list above.

# Enable Nonce for Scripts
CSP_INCLUDE_NONCE_IN = ['script-src']

CSP_DEFAULT_SRC = ["'self'"]

# Styling: Allow self, unsafe-inline (needed for dynamic styles), standard CDNs
CSP_STYLE_SRC = [
    "'self'", 
    "'unsafe-inline'", 
    "https://cdnjs.cloudflare.com", 
    "https://fonts.googleapis.com"
]

# Scripts: STRICTER - No unsafe-inline. Must have Nonce. 'strict-dynamic' allows trusted scripts to load dependencies.
CSP_SCRIPT_SRC = [
    "'self'", 
    "'strict-dynamic'",
    "https://cdnjs.cloudflare.com",
    "https://*.vercel.app" 
]

# Base URI: Prevent injection of <base> tags
CSP_BASE_URI = ["'self'"]

# Connect: Allow sending data (Critical for Vercel Speed Insights)
CSP_CONNECT_SRC = [
    "'self'", 
    "https://*.vercel-insights.com",
    "https://*.vercel-analytics.com",
    "https://res.cloudinary.com",
]

# Fonts: Allow self, Google Fonts data
CSP_FONT_SRC = [
    "'self'", 
    "https://fonts.gstatic.com", 
    "https://cdnjs.cloudflare.com", 
    "data:"
]

# Images: Allow self, base64, and any HTTPS
CSP_IMG_SRC = [
    "'self'", 
    "data:", 
    "https:",
]
